/* rbc.h — RBC C API. Auto-generated by cbindgen. DO NOT EDIT. */

#ifndef RBC_H
#define RBC_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

/**
 * RBC C API error codes. `RBC_ERROR_CODE_OK` is success; any other value is a failure
 * whose Rust-side Display-formatted reason is retrievable via
 * `rbc_last_error_message()` **on the same thread**.
 */
typedef enum {
  RBC_ERROR_CODE_OK = 0,
  RBC_ERROR_CODE_INVALID_ARG = 1,
  RBC_ERROR_CODE_CONFIG = 2,
  RBC_ERROR_CODE_TLS = 3,
  RBC_ERROR_CODE_PROVIDER = 4,
  RBC_ERROR_CODE_KEYGEN = 5,
  RBC_ERROR_CODE_EVIDENCE = 6,
  RBC_ERROR_CODE_NETWORK = 7,
  RBC_ERROR_CODE_TIMEOUT = 8,
  RBC_ERROR_CODE_AUTH = 9,
  RBC_ERROR_CODE_POLICY_DENIED = 10,
  RBC_ERROR_CODE_RESOURCE_NOT_FOUND = 11,
  RBC_ERROR_CODE_ATTEST = 12,
  RBC_ERROR_CODE_SERVER = 13,
  RBC_ERROR_CODE_ENCRYPT = 14,
  RBC_ERROR_CODE_DECRYPT = 15,
  RBC_ERROR_CODE_JSON = 16,
  RBC_ERROR_CODE_INTERNAL = 17,
} RbcErrorCode;

typedef struct RbcClient RbcClient;

typedef struct RbcResource RbcResource;

typedef struct RbcSession RbcSession;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Free a nul-terminated string returned by an RBC function.
 */
void RbcStringFree(char *s);

/**
 * Free a byte buffer returned by an RBC function. `len` MUST be the value
 * the producing call wrote into its `*out_len` parameter.
 */
void RbcBufferFree(uint8_t *buf, size_t len);

/**
 * Create a client from a YAML config file on disk.
 */
RbcErrorCode RbcClientNewFromFile(const char *config_path, RbcClient **out_client);

/**
 * Create a client from an in-memory YAML string.
 */
RbcErrorCode RbcClientNewFromYaml(const char *yaml, RbcClient **out_client);

/**
 * Destroy a client handle.
 */
void RbcClientFree(RbcClient *client);

/**
 * Fetch an authentication challenge. On success `*out_nonce` is a newly
 * allocated nul-terminated string owned by the caller; free with
 * `RbcStringFree`.
 */
RbcErrorCode RbcGetAuthChallenge(RbcClient *client, char **out_nonce);

/**
 * Return a pointer to the last error message set on the **current thread**, or
 * NULL if no error has been recorded since the last `rbc_last_error_clear` call.
 *
 * The returned pointer is valid until the next RBC API call on the same thread
 * (which may overwrite it) or the next `rbc_last_error_clear`. The caller MUST
 * NOT free it.
 */
const char *RbcLastErrorMessage(void);

/**
 * Clear the last error on the current thread.
 */
void RbcLastErrorClear(void);

/**
 * Borrow the URI. Valid until `RbcResourceFree`.
 */
const char *RbcResourceGetUri(const RbcResource *resource);

/**
 * Borrow the content-type (may be NULL). Valid until `RbcResourceFree`.
 */
const char *RbcResourceGetContentType(const RbcResource *resource);

/**
 * Borrow the raw content bytes. Writes the length into `*out_len`. Valid
 * until `RbcResourceFree`.
 */
const uint8_t *RbcResourceGetContent(const RbcResource *resource, size_t *out_len);

/**
 * Destroy a resource handle (invalidates all borrowed pointers obtained
 * from accessors).
 */
void RbcResourceFree(RbcResource *resource);

/**
 * Begin a new session. `attester_data_json` may be NULL. If non-NULL it must
 * be a JSON object matching `AttesterData` (per `rbs_api.yaml`); if its
 * `runtime_data.tee_pubkey` is present the caller is responsible for the
 * matching private key (pass it to `RbcSessionDecryptContent`).
 */
RbcErrorCode RbcSessionNew(RbcClient *client,
                           const char *attester_data_json,
                           RbcSession **out_session);

/**
 * Free a session. The embedded ephemeral key is zeroized on drop.
 */
void RbcSessionFree(RbcSession *session);

/**
 * Collect evidence for `nonce`. On success `*out_evidence_json` is a newly
 * allocated JSON-encoded nul-terminated string owned by the caller.
 */
RbcErrorCode RbcSessionCollectEvidence(RbcSession *session,
                                       const char *nonce,
                                       char **out_evidence_json);

/**
 * Exchange evidence for an attest token. `evidence_json` may be NULL (in
 * which case the session's TokenProvider must be able to produce a token
 * without one). On success `*out_token` is a newly allocated nul-terminated
 * string owned by the caller.
 */
RbcErrorCode RbcSessionAttest(RbcSession *session, const char *evidence_json, char **out_token);

/**
 * Fetch a resource using a previously-obtained attest token.
 */
RbcErrorCode RbcSessionGetResourceByToken(RbcSession *session,
                                          const char *uri,
                                          const char *token,
                                          RbcResource **out_resource);

/**
 * Fetch a resource using an evidence bundle (pull-by-evidence mode).
 */
RbcErrorCode RbcSessionGetResourceByEvidence(RbcSession *session,
                                             const char *uri,
                                             const char *evidence_json,
                                             RbcResource **out_resource);

/**
 * Decrypt a JWE token using the session's key.
 *
 * Pass `private_key_pem == NULL` to use the ephemeral key generated in
 * `RbcSessionBegin`. Pass a PEM string only when the caller supplied its own
 * `tee_pubkey` in `attester_data_json` during `RbcSessionBegin`.
 *
 * On success `*out_plaintext` is a newly allocated buffer of `*out_len` bytes
 * owned by the caller; release with `RbcBufferFree(buf, len)`.
 */
RbcErrorCode RbcSessionDecryptContent(RbcSession *session,
                                      const char *jwe,
                                      const char *private_key_pem,
                                      uint8_t **out_plaintext,
                                      size_t *out_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RBC_H */
